name: main

on: [push, workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz -O ngrok.tgz

    - name: Extract ngrok
      run: tar -xvzf ngrok.tgz

    - name: Install SSH server
      run: sudo apt-get update

    - name: Sleep for 1440 minutes
      uses: jakejarvis/wait-action@master
      with:
        time: '1440m'
